# coding: utf-8

"""
    Livepeer AI Runner

    An application to run AI pipelines

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from livepeer_ai_typed.models.image_response import ImageResponse  # noqa: E501

class TestImageResponse(unittest.TestCase):
    """ImageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageResponse:
        """Test ImageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageResponse`
        """
        model = ImageResponse()  # noqa: E501
        if include_optional:
            return ImageResponse(
                images = [
                    livepeer_ai_typed.models.media.Media(
                        url = '', 
                        seed = 56, )
                    ]
            )
        else:
            return ImageResponse(
                images = [
                    livepeer_ai_typed.models.media.Media(
                        url = '', 
                        seed = 56, )
                    ],
        )
        """

    def testImageResponse(self):
        """Test ImageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
