# coding: utf-8

"""
    Livepeer AI Runner

    An application to run AI pipelines

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from livepeer_ai_typed.models.text_to_image_params import TextToImageParams  # noqa: E501

class TestTextToImageParams(unittest.TestCase):
    """TextToImageParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextToImageParams:
        """Test TextToImageParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextToImageParams`
        """
        model = TextToImageParams()  # noqa: E501
        if include_optional:
            return TextToImageParams(
                model_id = '',
                prompt = '',
                height = 56,
                width = 56,
                guidance_scale = 1.337,
                negative_prompt = '',
                seed = 56,
                num_images_per_prompt = 56
            )
        else:
            return TextToImageParams(
                model_id = '',
                prompt = '',
        )
        """

    def testTextToImageParams(self):
        """Test TextToImageParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
