# coding: utf-8

"""
    Livepeer AI Runner

    An application to run AI pipelines

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from livepeer_ai_typed.models.api_error import APIError  # noqa: E501

class TestAPIError(unittest.TestCase):
    """APIError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIError:
        """Test APIError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIError`
        """
        model = APIError()  # noqa: E501
        if include_optional:
            return APIError(
                msg = ''
            )
        else:
            return APIError(
                msg = '',
        )
        """

    def testAPIError(self):
        """Test APIError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
