=begin
#Livepeer AI Runner

#An application to run AI pipelines

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/api_error'
require 'openapi_client/models/http_error'
require 'openapi_client/models/http_validation_error'
require 'openapi_client/models/health_check'
require 'openapi_client/models/image_response'
require 'openapi_client/models/media'
require 'openapi_client/models/text_to_image_params'
require 'openapi_client/models/validation_error'
require 'openapi_client/models/validation_error_loc_inner'
require 'openapi_client/models/video_response'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
