/**
 * Livepeer AI Runner
 * An application to run AI pipelines
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Media } from '../models/Media';
import { HttpFile } from '../http/http';

export class ImageResponse {
    'images': Array<Media>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Media>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImageResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

