# coding: utf-8

"""
    Livepeer AI Runner

    An application to run AI pipelines

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from livepeer_ai.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_image_to_image(self) -> None:
        """Test case for image_to_image

        Image To Image
        """
        pass

    def test_image_to_video(self) -> None:
        """Test case for image_to_video

        Image To Video
        """
        pass

    def test_text_to_image(self) -> None:
        """Test case for text_to_image

        Text To Image
        """
        pass

    def test_upscale(self) -> None:
        """Test case for upscale

        Upscale
        """
        pass


if __name__ == '__main__':
    unittest.main()
