# coding: utf-8

"""
    Livepeer AI Runner

    An application to run AI pipelines

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from livepeer_ai.models.video_response import VideoResponse

class TestVideoResponse(unittest.TestCase):
    """VideoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoResponse:
        """Test VideoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VideoResponse`
        """
        model = VideoResponse()
        if include_optional:
            return VideoResponse(
                images = [
                    livepeer_ai.models.media.Media(
                        url = '', 
                        seed = 56, 
                        nsfw = True, )
                    ]
            )
        else:
            return VideoResponse(
                images = [
                    livepeer_ai.models.media.Media(
                        url = '', 
                        seed = 56, 
                        nsfw = True, )
                    ],
        )
        """

    def testVideoResponse(self):
        """Test VideoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
