=begin
#Livepeer AI Runner

#An application to run AI pipelines

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::HealthCheck
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::HealthCheck do
  let(:instance) { OpenapiClient::HealthCheck.new }

  describe 'test an instance of HealthCheck' do
    it 'should create an instance of HealthCheck' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::HealthCheck)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
