=begin
#Livepeer AI Runner

#An application to run AI pipelines

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ImageResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ImageResponse do
  let(:instance) { OpenapiClient::ImageResponse.new }

  describe 'test an instance of ImageResponse' do
    it 'should create an instance of ImageResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ImageResponse)
    end
  end

  describe 'test attribute "images"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
