/**
 * Livepeer AI Runner
 * An application to run AI pipelines
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIError } from '../models/APIError';
import { HttpFile } from '../http/http';

export class HTTPError {
    'detail': APIError;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "detail",
            "baseName": "detail",
            "type": "APIError",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HTTPError.attributeTypeMap;
    }

    public constructor() {
    }
}

