/**
 * Livepeer AI Runner
 * An application to run AI pipelines
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Media {
    'url': string;
    'seed': number;
    'nsfw': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "seed",
            "baseName": "seed",
            "type": "number",
            "format": ""
        },
        {
            "name": "nsfw",
            "baseName": "nsfw",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Media.attributeTypeMap;
    }

    public constructor() {
    }
}

