/**
 * Livepeer AI Runner
 * An application to run AI pipelines
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LivepeerAiRunner);
  }
}(this, function(expect, LivepeerAiRunner) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LivepeerAiRunner.Media();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Media', function() {
    it('should create an instance of Media', function() {
      // uncomment below and update the code to test Media
      //var instance = new LivepeerAiRunner.Media();
      //expect(instance).to.be.a(LivepeerAiRunner.Media);
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new LivepeerAiRunner.Media();
      //expect(instance).to.be();
    });

    it('should have the property seed (base name: "seed")', function() {
      // uncomment below and update the code to test the property seed
      //var instance = new LivepeerAiRunner.Media();
      //expect(instance).to.be();
    });

    it('should have the property nsfw (base name: "nsfw")', function() {
      // uncomment below and update the code to test the property nsfw
      //var instance = new LivepeerAiRunner.Media();
      //expect(instance).to.be();
    });

  });

}));
