=begin
#Livepeer AI Runner

#An application to run AI pipelines

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for image_to_image
  # Image To Image
  # @param prompt 
  # @param image 
  # @param model_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :strength 
  # @option opts [Float] :guidance_scale 
  # @option opts [Float] :image_guidance_scale 
  # @option opts [String] :negative_prompt 
  # @option opts [Boolean] :safety_check 
  # @option opts [Integer] :seed 
  # @option opts [Integer] :num_images_per_prompt 
  # @return [ImageResponse]
  describe 'image_to_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for image_to_video
  # Image To Video
  # @param image 
  # @param model_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :height 
  # @option opts [Integer] :width 
  # @option opts [Integer] :fps 
  # @option opts [Integer] :motion_bucket_id 
  # @option opts [Float] :noise_aug_strength 
  # @option opts [Integer] :seed 
  # @option opts [Boolean] :safety_check 
  # @return [VideoResponse]
  describe 'image_to_video test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for text_to_image
  # Text To Image
  # @param text_to_image_params 
  # @param [Hash] opts the optional parameters
  # @return [ImageResponse]
  describe 'text_to_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upscale
  # Upscale
  # @param prompt 
  # @param image 
  # @param model_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :safety_check 
  # @option opts [Integer] :seed 
  # @return [ImageResponse]
  describe 'upscale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
