/**
 * Livepeer AI Runner
 * An application to run AI pipelines
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Media from './Media';

/**
 * The ImageResponse model module.
 * @module model/ImageResponse
 * @version 0.1.0
 */
class ImageResponse {
    /**
     * Constructs a new <code>ImageResponse</code>.
     * @alias module:model/ImageResponse
     * @param images {Array.<module:model/Media>} 
     */
    constructor(images) { 
        
        ImageResponse.initialize(this, images);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, images) { 
        obj['images'] = images;
    }

    /**
     * Constructs a <code>ImageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImageResponse} obj Optional instance to populate.
     * @return {module:model/ImageResponse} The populated <code>ImageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageResponse();

            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [Media]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ImageResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ImageResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ImageResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['images']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['images'])) {
                throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
            }
            // validate the optional field `images` (array)
            for (const item of data['images']) {
                Media.validateJSON(item);
            };
        }

        return true;
    }


}

ImageResponse.RequiredProperties = ["images"];

/**
 * @member {Array.<module:model/Media>} images
 */
ImageResponse.prototype['images'] = undefined;






export default ImageResponse;

