/**
 * Livepeer AI Runner
 * An application to run AI pipelines
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Media from './Media';

/**
 * The VideoResponse model module.
 * @module model/VideoResponse
 * @version 0.1.0
 */
class VideoResponse {
    /**
     * Constructs a new <code>VideoResponse</code>.
     * @alias module:model/VideoResponse
     * @param frames {Array.<Array.<module:model/Media>>} 
     */
    constructor(frames) { 
        
        VideoResponse.initialize(this, frames);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, frames) { 
        obj['frames'] = frames;
    }

    /**
     * Constructs a <code>VideoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoResponse} obj Optional instance to populate.
     * @return {module:model/VideoResponse} The populated <code>VideoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoResponse();

            if (data.hasOwnProperty('frames')) {
                obj['frames'] = ApiClient.convertToType(data['frames'], [[Media]]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VideoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VideoResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VideoResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['frames'])) {
            throw new Error("Expected the field `frames` to be an array in the JSON data but got " + data['frames']);
        }

        return true;
    }


}

VideoResponse.RequiredProperties = ["frames"];

/**
 * @member {Array.<Array.<module:model/Media>>} frames
 */
VideoResponse.prototype['frames'] = undefined;






export default VideoResponse;

